# Generated by Django 6.0.2 on 2026-02-15 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Утвержден'), ('rejected', 'Отклонен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='users.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to='users.employee')),
            ],
            options={
                'verbose_name': 'Заявка на отпуск',
                'verbose_name_plural': 'Заявки на отпуск',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacationBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(verbose_name='Год')),
                ('total_days', models.FloatField(default=28, verbose_name='Всего дней')),
                ('used_days', models.FloatField(default=0, verbose_name='Использовано дней')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_balances', to='users.employee')),
            ],
            options={
                'verbose_name': 'Баланс отпуска',
                'verbose_name_plural': 'Балансы отпусков',
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
