# Generated by Django 6.0.2 on 2026-02-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='current_step',
            field=models.PositiveIntegerField(default=1, verbose_name='Текущий шаг'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='step_history',
            field=models.JSONField(blank=True, default=list, verbose_name='История прохождения шагов'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='step_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало текущего шага'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('in_approval', 'На согласовании'), ('approved', 'Утверждён'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vacation', 'Отпуск'), ('business_trip', 'Командировка')], max_length=20, verbose_name='Тип заявления')),
                ('step_no', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('role', models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Руководитель'), ('hr', 'HR-специалист')], max_length=20, verbose_name='Роль')),
                ('sla_days', models.PositiveIntegerField(default=1, verbose_name='Срок согласования (дней)')),
            ],
            options={
                'verbose_name': 'Маршрут согласования',
                'verbose_name_plural': 'Маршруты согласования',
                'ordering': ['type', 'step_no'],
                'unique_together': {('type', 'step_no')},
            },
        ),
    ]
