# Generated by Django 6.0.2 on 2026-02-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_vacationrequest_current_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='request_type',
            field=models.CharField(choices=[('vacation', 'Отпуск'), ('business_trip', 'Командировка')], default='vacation', max_length=20, verbose_name='Тип заявления'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('in_approval', 'На согласовании'), ('approved', 'Утверждён'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
